const { Telegram } = require("telegraf");

// Stable Telegram file_ids generated by the bot itself after importing the HD visuals.
// Keeping them here avoids depending on temporary external image URLs on future restarts.
const HD_ASSETS = {
  home: "AgACAgQAAyEGAAMBB5cF3wACAaBqw5qG_ZZN2fyrcbQ0-audpAldqwAC6Q5rG3uTJFKC9JPLe5GNNAEAAwIAA3cAAz0E",
  paypal: "AgACAgQAAyEGAAMBB5cF3wACAaFqw5qHNmC656_mIevylLKYx1XJfAAC7w5rG7dfJVI6Xt6BhNGMZQEAAwIAA3cAAz0E",
  paysafecard: "AgACAgQAAyEGAAMBB5cF3wACAaJqw5qJc6DS8CqFCw8bmZpMkTYhIQAC8w5rG5FdHFIj54JZgMCznAEAAwIAA3cAAz0E",
  yonibet: "AgACAgQAAyEGAAMBB5cF3wACAaNqw5qLdnmCJdAbUdnniIV-cDEHUAACBg9rG428JVKJ5lNk44F_xQEAAwIAA3cAAz0E",
  proof: "AgACAgQAAyEGAAMBB5cF3wACAaRqw5qMiql23NJpexGdkKGSCwKeogAC7Q5rG6BwHVKqJMuTzUJc0QEAAwIAA3cAAz0E",
  pending: "AgACAgQAAyEGAAMBB5cF3wACAaVqw5qOE3bVycPT1rqJfimPCmMZRwACAw9rG6ycJFLYBmtKIDa12gEAAwIAA3cAAz0E",
  approved: "AgACAgQAAyEGAAMBB5cF3wACAaZqw5qQbAgd_8UZL1r3CKiHNqvvOAAC_w5rG53YHVLHUmT9apQk9gEAAwIAA3cAAz0E",
  rejected: "AgACAgQAAyEGAAMBB5cF3wACAadqw5qRqNi7VGoxnM3XOVFAZmbGjAACzQ5rG46lJFKUYzqx2xMGTAEAAwIAA3cAAz0E",
  help: "AgACAgQAAyEGAAMBB5cF3wACAahqw5qSPWael9NY_KmcZov-YQ5S0QACtw5rG-MSJVLNs6IhER9FaQEAAwIAA3cAAz0E",
};

function hdAssetFor(media) {
  if (!media || typeof media === "string") return null;
  const filename = String(media.filename || "");
  const match = filename.match(/^([a-z]+)\.jpg$/i);
  return match ? HD_ASSETS[match[1]] || null : null;
}

if (Telegram?.prototype?.sendPhoto) {
  const originalSendPhoto = Telegram.prototype.sendPhoto;
  Telegram.prototype.sendPhoto = function hdSendPhoto(chatId, photo, extra) {
    return originalSendPhoto.call(this, chatId, hdAssetFor(photo) || photo, extra);
  };
}

if (Telegram?.prototype?.editMessageMedia) {
  const originalEditMessageMedia = Telegram.prototype.editMessageMedia;
  Telegram.prototype.editMessageMedia = function hdEditMessageMedia(
    chatId,
    messageId,
    inlineMessageId,
    media,
    extra
  ) {
    const replacement = hdAssetFor(media?.media);
    const nextMedia = replacement ? { ...media, media: replacement } : media;
    return originalEditMessageMedia.call(
      this,
      chatId,
      messageId,
      inlineMessageId,
      nextMedia,
      extra
    );
  };
}

module.exports = { HD_ASSETS };
